### ISSUE TITLE
Hide Serf and Raft from Broker

### ISSUE THREAD

**Issue by shwetabhgarg** [travisjeffery/jocko#22]
Issue: Broker struct is over-burdened.
Proposal: Hide details of serf and raft from Broker behind interfaces
Potential benefits?:
1. Responsibility of broker package becomes leaner, making it easier to navigate
2. Easier to write fine-grained tests of functionalities by mocking out serf and raft interfaces, and separate testing for serf and raft functionalities

Code changes proposal: [Feature branch](https://github.com/travisjeffery/jocko/compare/master...shwetabhgarg:broker_cleanup)
This change set moves serf/raft code from broker to outside. All tests pass.
Next steps (todo):
- write tests by mocking out serf and raft

**Comment by travisjeffery** [comment]
Hey, thanks for the PR it looks pretty good. I thought about doing this before, but I was/am a bit hesitant since Raft's FSM and the broker have such similar roles. Turning the broker into the FSM might be one idea. I like what you've done thus far and am warming up to. Could you make a PR for it and rebase the latest command arg changes I merged?

**Comment by shwetabhgarg** [comment]
Will do. Will make a PR once done.

**Comment by travisjeffery** [comment]
Gonna close this issue. Make another issue/PR when you've got some more stuff to look at. Thanks.
